# Generated by Django 4.2.27 on 2026-01-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('n_caja', models.CharField(max_length=255)),
                ('denominacion', models.CharField(max_length=255)),
                ('n_hojas', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
