# Generated by Django 5.1.6 on 2025-12-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('denominacion', models.CharField(max_length=255)),
                ('numero_caja', models.IntegerField()),
                ('numero_hojas', models.IntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
