# Generated by Django 4.2.27 on 2026-01-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrodocumento',
            table='archivos',
        ),
    ]
