# Generated by Django 4.2.27 on 2026-01-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrodocumento',
            options={'managed': False},
        ),
    ]
